name: swiftlane集成开发APP
# 触发条件
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches:
    - '*'
# 执行的任务
jobs:
  swiftlane:
    runs-on: macos-latest
    steps:
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1.18.0
    - name: Repository checkout
      uses: actions/checkout@v2
    - name: 执行swiftlane暂存操作
      id: cache-swiftlane
      uses: actions/cache@v3
      with:
        path: |
          ~/work/_actions/it-boyer/iFastlane/main
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-swiftlane
    - if: ${{ steps.cache-swiftlane.outputs.cache-hit != 'true' }}
      name: 安装swiftlane
      uses: it-boyer/iFastlane@main
      with:
        argOne: 'build'
    # 暂存无法对环境变量设置，不知道如何获取action路径,目前手动设置
    - name: 恢复环境变量,安装brew插件
      run: |
        echo "/Users/runner/work/_actions/it-boyer/iFastlane/main" >> $GITHUB_PATH
        cd /Users/runner/work/_actions/it-boyer/iFastlane/main
        brew bundle
    - name: 使用swiftlane
      run: swifttlane lane swiftBuild
