name: 测试unitdemo命令
# 触发条件
on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'
# 执行的任务
jobs:
  unit_tests:
    runs-on: macos-latest
    steps:
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1.18.0
    - name: 使用swift命令,打印swfit版本
      run: |
        swift --version
      shell: swift {0}  #swift must be installed on the runne

    - name: Repository checkout
      uses: actions/checkout@v2
    - name: Build for macOS
      uses: it-boyer/UnitDemo@main
      with:
        argOne: 'build'
