name: 测试unitdemo命令
# 触发条件
on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'
# 执行的任务
jobs:
  unit_tests:
    runs-on: macos-latest
    steps:
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1.18.0
    - name: Repository checkout
      uses: actions/checkout@v2
    - name: hhh
      uses: it-boyer/UnitDemo@main #使用本地文件action
      with:
          who-to-greet: 'Mona the Octocat'
