name: 测试githubworkflow语法
# 触发条件
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'
# 执行的任务
jobs:
  hello_job:
    runs-on: macos-latest
    # defaults:
      # run:
        # working-directory: /Users/runner
    steps:
    - name: Repository checkout
      uses: actions/checkout@v2
    - name: 远程文件脚本
      run: .github/remote-run it-boyer/UnitDemo Unit --a 我是远程swift脚本
