name: 测试githubworkflow语法
# 触发条件
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'
# 执行的任务
jobs:
  hello_job:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: /Users/runner
    steps:
    - name: Repository checkout
      uses: actions/checkout@v2
    - name: 使用cache
      id: cache-unitdemo
      uses: actions/cache@v3
      env:
        cache-name: cache-unitdemo
      with:
        path: |
          ~/testdir
        key: ${{ runner.os }}-${{ env.cache-name }}
    - name: shell默认目录
      run: |
        pwd
        ls -al
        mkdir testdir
        echo "使用暂存" >> testdir/cache.txt
        cat testdir/cache.txt
        ls -al

    - name: 暂存 swift
      uses: actions/cache@v3
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - if: ${{ steps.cache-unitdemo.outputs.cache-hit != 'true' }}
      name: 无缓存记录
      run: ls -al
