name: 部署发布iPA包
# 触发条件
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches:
    - '*'
# 执行的任务
jobs:
  swiftlane:
    runs-on: macos-latest
    steps:
    - name: Repository checkout
      uses: actions/checkout@v2
    - name: 执行swiftlane暂存操作
      id: cache-swiftlane
      uses: actions/cache@v3
      with:
        path: iFastlane
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - if: ${{ steps.cache-swiftlane.outputs.cache-hit != 'true' }}
      name: 安装swiftlane
      run: |
        git clone git@github.com/it-boyer/iFastlane.git
        cd iFastlane
        swift build
      shell: bash

    - name: 发布iPA
      run: .build/debug/Runner lane swiftBuild
      working-directory: iFastlane
      shell: bash
