name: blink方法部署发布iPA包
# 触发条件
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches:
    - '*'
# 执行的任务
jobs:
  swiftlane:
    runs-on: macos-latest
    steps:
    - name: Repository checkout
      uses: actions/checkout@v2
    - name: 执行swiftlane暂存操作
      id: cache-swiftlane
      uses: actions/cache@v3
      with:
        path: ~/work/iFastlane
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - if: ${{ steps.cache-swiftlane.outputs.cache-hit != 'true' }}
      name: 安装swiftlane
      working-directory: /Users/runner/work
      run: |
        pwd
        git clone https://github.com/it-boyer/iFastlane.git
        cd iFastlane
        swift build
      shell: bash

    - if: ${{ steps.cache-swiftlane.outputs.cache-hit == 'true' }}
      name: 更新swiftlane
      working-directory: /Users/runner/work/iFastlane
      run: |
        git pull origin main
        swift build
        echo "~/work/iFastlane/.build/debug/" >> $GITHUB_PATH
        brew bundle
      shell: bash

    - name: lane生成不签名的测试包
      run: Runner lane blinkBuild
      shell: bash

    - name: upload ipa
      uses: actions/upload-artifact@v2.2.0
      with:
        name: 'FastlaneDemo'
        path: FastlaneDemo.ipa

    - name: 制作iPA上传到apptize服务器上
      run: |
          mkdir Payload
          mv build/*/Products/Applications/FastlaneDemo.app Payload/
          zip -r FastlaneDemo.ipa Payload
          Runner lane appetize path FastlaneDemo.ipa
