name: 测试unitdemo命令
# 触发条件
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches:
     - '*'
# 执行的任务
jobs:
  Unit_job:
    runs-on: macos-latest
    steps:
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1.18.0
    - name: Repository checkout
      uses: actions/checkout@v2
    - name: 执行UnitDemo暂存操作
      id: cache-unitdemo
      uses: actions/cache@v3
      with:
        path: |
          ~/work/_actions/it-boyer/UnitDemo/main
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    #判断unit是否安装
    - if: ${{ steps.cache-unitdemo.outputs.cache-hit != 'true' }}
      name: 安装Unit瑞士军刀
      uses: it-boyer/UnitDemo@main
      with:
        argOne: 'build'
    - name: 恢复环境变量
      shell: bash
      run: echo $GITHUB_PATH && echo "测试：${{ github.action_path }}" && echo "/Users/runner/work/_actions/it-boyer/UnitDemo/main" >> $GITHUB_PATH
    #使用Unit工具
    - name: 使用Unit处理检查操作
      run: |
        # 暂存无法对环境变量设置，不知道如何获取action路径,目前手动设置
        #echo "${{ github.action_path }}" >> $GITHUB_PATH
        Unit --a 测试Unit
